### ISSUE TITLE
Kidokuskip-related commands are useful and should be implemented

### ISSUE THREAD

**Issue by ghost** [Helios-vmg/ONSlaught#5]
http://nscripter.insani.org/reference/
'Unimplemented commands (commands that will probably remain so): [...] kidokumode, kidokuskip, etc.' (if I recall correctly, there are other commands related to it)

**Comment by Helios-vmg** [comment]
Implementing kidokuskip would involve too much work. Right now I'm only willing to fix outright broken things or to add functionality that's simple to implement.

**Comment by ghost** [comment]
Understandable, that's a minor improvement after all.
